### ISSUE TITLE
kdominos: game always starts with same initial state

### ISSUE THREAD

**Issue by BartMassey** [keith-packard/kgames#11]
It appears that the PRNG is not seeded for kdominos: starting a new game not from a save file (at least) always starts with the same racks for both sides, and continues with same draws.

**Comment by BartMassey** [comment]
Turns out that if `$HOME/.dominos` exists, the new game state is silently read from there. Remove it to get a new game each time. Should probably not work quite like this.

**Comment by keith-packard** [comment]
How about I stick up a message about resuming existing game?

**Comment by keith-packard** [comment]
I'm gonna call this one 'fixed' with the new message. https://github.com/keith-packard/kgames/commit/5e2916174059061e8321e769b8643aad6be0fe03
