### ISSUE TITLE
Avoid using case-sensitive filenames

### ISSUE THREAD

**Issue by mohd-akram** [keith-packard/kgames#21]
I get this when I clone the project on macOS:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'dominos/Dominos.c'
  'dominos/dominos.c'
  'dominos/Dominos.h'
  'dominos/dominos.h'
  'reversi/Reversi.h'
  'reversi/reversi.h'
  'Xkw/Layout.c'
  'Xkw/layout.c'
```

**Comment by BartMassey** [comment]
I'm not a Mac user, but it looks like MacOS filesystems can be configured to be case-sensitive but default to not. For software dev, I would suggest case-sensitive.

That said, I've pushed a branch `case-insensitive` here that should solve your immediate problem. I will wait for Keithp to process a pull request before trying to move these changes into `main`.
