### ISSUE TITLE
kklondike: various dragging issues

### ISSUE THREAD

**Issue by BartMassey** [keith-packard/kgames#24]
Now that the dragging is merged, there's a few things I noticed while trying out `kklondike`. Probably other games are similarly affected, but I don't remember how to play most of them. :slightly_smiling_face: 

* Must click to turn the pile. Should be able to drag.
* Dragging a card leaves a duplicate of it until dragging is complete, which is confusing. Should switch to whatever is underneath as drag starts.
* Dragging a stack only drags the bottom card, leaving the cards on top of it with its duplicate until dragging is complete. Should drag the card and everything above it.
* For some reason I got all but one black cards at the start of my game. That's not fair! :grinning:

**Comment by keith-packard** [comment]
> Now that the dragging is merged, there's a few things I noticed while trying out `kklondike`. Probably other games are similarly affected, but I don't remember how to play most of them. slightly_smiling_face

Need to add rules; cribbing from the palm pilot 'patience' app should be easy.

>     * Must click to turn the pile. Should be able to drag.

Good point. Will be easy to fix.

>     * Dragging a card leaves a duplicate of it until dragging is complete, which is confusing. Should switch to whatever is underneath as drag starts.

Yeah, that's a bunch harder -- would need to 'move' the cards to the dragging widget and 'move' them to whereever they end up. The current implementation just creates a new temporary card.

>     * Dragging a stack only drags the bottom card, leaving the cards on top of it with its duplicate until dragging is complete. 
Should drag the card and everything above it.

That should be easier to do; just copy all of the relevant cards into a stack for the new widget, resize it as needed and drag away.

>     * For some reason I got all but one black cards at the start of my game. That's not fair! grinning

I stuck special code to detect your user name and make the games harder to win.

**Comment by BartMassey** [comment]
> Yeah, that's a bunch harder -- would need to 'move' the cards to the dragging widget and 'move' them to wherever they end up. The current implementation just creates a new temporary card.

Can you just temporarily flip the original to face down while dragging the copy, then flip it back when done?
