### ISSUE TITLE
kcribbage: spurious keypress

### ISSUE THREAD

**Issue by BartMassey** [keith-packard/kgames#3]
~~Accidentally clicking when prompted for hand score causes a
complaint from kcribbage.~~

Typing a 'space' when prompted with `--More--` will cause that space to be fed to an immediate input prompt. Or something similar.

**Comment by keith-packard** [comment]
I'm betting this is another resource issue. dang, Xt can be messed up by X resources something fierce.

**Comment by BartMassey** [comment]
We saw this happen a bit ago: turns out this bug description was terrible. It's apparently that the space typed at the "more" prompt can be interpreted as input text. No clicking is involved.

**Comment by BartMassey** [comment]
This seems to be fixed now. Will close until I see it again.
