### ISSUE TITLE
Some played cards do not show in transcript

### ISSUE THREAD

**Issue by BartMassey** [keith-packard/kgames#52]
![image](https://user-images.githubusercontent.com/117151/148856790-6ef7ed77-b84d-49e2-b12c-aa7a5a79d69e.png)

As far as I can tell the computer should have scored 4, not 5 on that last play: 3 for the run and 1 for the go (which also mysteriously didn't appear).

Keith and I looked at the bug carefully and can't see what happened.

It will remain a mystery for now.

**Comment by keith-packard** [comment]
Ah, the computer doesn't print the cards it plays unless it pegs points. As you can see, the computer has only one card remaining, and so the other card must have been a 2 so that the total of 2 + 7 + 7 + 6 + 8 = 31. The final 8 pegs 5 points, and moves to the next round.

**Comment by BartMassey** [comment]
It must have been a 3, because 7 + 7 + 6 + 8 = 28. But yeah.

I think it would be better if the log showed all plays by both sides: it makes it far easier to follow the play scoring, and I don't see much downside…
