### ISSUE TITLE
kdominos: Set contains two double-blanks

### ISSUE THREAD

**Issue by BartMassey** [keith-packard/kgames#9]
Don't remember exactly how a set of double-nine dominos is supposed to work, but was surprised to find two blank-blank dominos in play.

**Comment by keith-packard** [comment]
Looks like 'normal' sets have 55 dominos, which would correspond to just one double-zero.

**Comment by keith-packard** [comment]
I must have modeled this after a set that had two double-zero dominos; there's an explicit 'create another 0 0 domino' piece of code. I'll remove that.

**Comment by keith-packard** [comment]
Fixed in https://github.com/keith-packard/kgames/commit/4489d5f0dd2c0ac6bbdebc5761724404bada6d27
